##mysql config
spring.mysql.url=jdbc:p6spy:mysql://qa-liveconnect.mysql.database.azure.com/order_buk_new?zeroDateTimeBehavior=convertToNull
spring.mysql.username=obuk@qa-liveconnect
spring.mysql.password=Orderbuklc123
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect


#Dev only
spring.mysql.driverClassName=com.p6spy.engine.spy.P6SpyDriver

spring.jpa.properties.hibernate.jdbc.batch_size=5000
spring.mysql.hikari.poolName=SpringBootJPAHikariCP
spring.mysql.hikari.connectionTimeout=300000
spring.mysql.hikari.idleTimeout=200000
spring.mysql.hikari.maxLifetime=600000
spring.mysql.hikari.maximumPoolSize=5
spring.mysql.hikari.minimumIdle=2

spring.mysql.testWhileIdle=true
spring.mysql.validationQuery=SELECT 1

#spring.data.mongodb.host = 52.172.212.179
spring.data.mongodb.host = 10.10.0.21
spring.data.mongodb.port = 27017
spring.data.mongodb.database = ms_customer_creation
#spring.data.mongodb.username = qamsadmin
spring.data.mongodb.username = devmsadmin
#spring.data.mongodb.password = q@MsAdmin@213
spring.data.mongodb.password = SDXxXQFdkExkFq8j
spring.data.mongodb.authentication-database = admin

spring.data.mongodb.keepAlive=true
spring.data.mongodb.poolSize=5
spring.data.mongodb.autoReconnect=true
spring.data.mongodb.socketTimeoutMS=120000
spring.data.mongodb.connectTimeoutMS=12000