##Added correct port number
server.port=1860
fetch.max.size.limit = 5000

#For Session Id
aes.key = 9z$C&F)J@NcRfUjWnZr4u7x!A%D*G-Ka
aes.iv = fSdtT8WMdzVpXDcM

spring.liquibase.enabled=false

cors.url=http://localhost:3000

#JWT Token Properties
jwt.secret=mySecret
jwt.header=Authorization
jwt.header.prefix=Bearer
jwt.access.token.expiration=86400000
jwt.refresh.token.expiration=864000000

secret.key=ajay123
hash.algorithm=HmacSHA256

auth.retry.attempts=5
cors.url.list=http://localhost:3000,https://lcpwaliveconnectblob.z29.web.core.windows.net/