## PostgreSQL
spring.datasource.url=jdbc:postgresql://10.10.0.21:5402/ms_auth
spring.datasource.username=postgres
spring.datasource.password=ZZ3g3REChYYbNbz6

spring.datasource.hikari.poolName=SpringBootJPAHikariCP
spring.datasource.hikari.connectionTimeout=20000
spring.datasource.hikari.idleTimeout=30000
spring.datasource.hikari.maxLifetime=60000
spring.datasource.hikari.maximumPoolSize=5
spring.datasource.hikari.minimumIdle=2

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL94Dialect

#dev only
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
log4j.logger.org.hibernate.type=trace 
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

#spring.data.mongodb.host = 52.172.212.179
spring.data.mongodb.host = 10.10.0.21
spring.data.mongodb.port = 27017
spring.data.mongodb.database = ms_customer_creation
#spring.data.mongodb.username = qamsadmin
spring.data.mongodb.username = devmsadmin
#spring.data.mongodb.password = q@MsAdmin@213
spring.data.mongodb.password = SDXxXQFdkExkFq8j
spring.data.mongodb.authentication-database = admin

