server.port =1992

fetch.max.size.limit=5000
log4j.logger.org.hibernate.engine.internal.StatisticalLoggingSessionEventListener=OFF

azure.eventhub.connection.string=Endpoint=sb://ms-combine.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=iaoAHOV75xtZCjNoAvImnhJpcFyN8+nZLe3eMWPtycI=
azure.eventhub.combine.name=dev-ms-combine

spring.liquibase.enabled=false