spring.jpa.database=POSTGRESQL
spring.datasource.platform=postgres
spring.datasource.driverClassName=com.p6spy.engine.spy.P6SpyDriver
spring.datasource.url=jdbc:p6spy:postgresql://10.39.0.4:5432/ms_customer
spring.datasource.username=postgres
spring.datasource.password=ZZ3g3REChYYbNbz6
spring.datasource.hikari.poolName=SpringBootJPAHikariCPCust

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.datasource.hikari.connectionTimeout=300000
spring.datasource.hikari.idleTimeout=200000
spring.datasource.hikari.maxLifetime=250000
spring.datasource.hikari.maximumPoolSize=5
spring.datasource.hikari.minimumIdle=2

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


#dev only
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.generate_statistics=true

#mongoDb
#spring.data.mongodb.host = 10.31.0.131
spring.data.mongodb.host = 10.39.0.4
spring.data.mongodb.port = 27017
spring.data.mongodb.database = ms_masters_cache
#spring.data.mongodb.username = qamsadmin
spring.data.mongodb.username = devadmin
#spring.data.mongodb.password = q@MsAdmin@213
spring.data.mongodb.password = SDXxXQFdkExkFq8j
spring.data.mongodb.authentication-database = admin

spring.data.mongodb.keepAlive=true
spring.data.mongodb.poolSize=5
spring.data.mongodb.autoReconnect=true
spring.data.mongodb.socketTimeoutMS=120000
spring.data.mongodb.connectTimeoutMS=12000