##
server.port=2260

api.base.path=/c2/lc/ms/mst
search.endpoint=/c2/lc/ms/mst/search/l

fetch.max.size.limit=5000

fast.moving.fetch.size=10
spring.liquibase.enabled=false

spring.elasticsearch.rest.uris=https://b63d5c24a7cc4e45866a8f066b8b70ba.southcentralus.azure.elastic-cloud.com:9243
spring.elasticsearch.rest.connection-timeout=30s
spring.elasticsearch.rest.read-timeout=1m
spring.elasticsearch.rest.password=liveorder123
spring.elasticsearch.rest.username=live_user
#logging.level.org.elasticsearch.client=TRACE

spring.main.allow-bean-definition-overriding=true

#cors.url=*

cors.url.list=http://localhost:3000,https://lcpwaliveconnectblob.z29.web.core.windows.net/

#Local
#master.service.url=http://localhost:8919

#Dev
master.service.url=http://10.0.180.124:2261

#DEV
ms.firm.service.api.url=http://10.0.131.108:1960/c2/lc/ms/cust/firm/detail

#Local
#ms.firm.service.api.url = http://localhost:1960/c2/lc/ms/cust/firm/detail

#local
#ms.cust.mapped.service.api.url=http://localhost:1960/c2/lc/ms/cust/seller/mapped/seller

#local
#ms.cust.seller.service.api.url=http://localhost:1960/c2/lc/ms/cust/seller/firm/seller

#local
save.recent.items.api=http://localhost:1960/c2/lc/ms/cust/b2c/save/recent/items
get.recent.items.api=http://localhost:1960/c2/lc/ms/cust/b2c/get/recent/items

#Dev
ms.cust.mapped.service.api.url=http://localhost:1960/c2/lc/ms/cust/seller/mapped/seller

#Dev
ms.cust.seller.service.api.url=http://10.0.131.108:1960/c2/lc/ms/cust/seller/firm/seller

netmeds.item-push.api=https://aff.netmeds.com/nmspushitems/api/product/add-product
netmeds.item-push.api.basic-auth.username=nmscsuser
netmeds.item-push.api.basic-auth.password=u67gjlp!kasdo

netmeds.customer-creation.api=https://dev-rwos.netmeds.com/nma/v01/b2bcustomers?cmd=create&branchCode=000
netmeds.customer-creation.api.basic-auth.username=CSquareB2B
netmeds.customer-creation.api.basic-auth.password=3V9@kRhzKr3QjI80

#please changes RRL api endpoint in prod
eg.customer-creation.api=https://qa-eg-eco.livc.in/eco/live/create-customer
eg.customer-creation.authorization=Basic Q1NxdWFyZUIyQjozVjlAa1JoektyM1FqSTgw

merchant.onboarding.url=https://qa-lc.livc.in/po/l/lo/grab-store-registration
nm.store.registeration.url=https://stg-win.netmeds.com/ccenter/api/v1/stores/addorupdate
nm.store.status.detail.url=https://stg-win.netmeds.com/ccenter/api/v1/stores/
nm.new.store.registeration.authorization=U3RnLUNzcXVhcmVVc2VyOlN0Z0NAMDEh

#days for new launch
new.launch.days=90

#Azure blob storage
azure.storage.connection.string=DefaultEndpointsProtocol=https;AccountName=devlcms;AccountKey=N5EIziU/SpzikCtwzaPmthJyX2GcUGacIKkVtPX7IYre05d5YZZdTD5RsAyUSn7S4Ur8sNvDBYEJ7tPS3F76SQ==;EndpointSuffix=core.windows.net
azure.storage.container.name=dev-msliveconnet

#spring.cache.type=redis
#spring.redis.host=liveorder.redis.cache.windows.net
#spring.redis.port=6379
#spring.redis.password=CDuOucVMnHlUBjbD5gUwj59fb713zTQqBJYqLYoL8xY=
#spring.redis.ssl=false

#QA
#lc.search.api=http://172.27.0.37:1960/c2/lc/ms/cust/na/search/lc

#localhost
#lc.search.api=http://localhost:1960/c2/lc/ms/cust/na/search/lc1

#QA
#customer.confirm.item.api=http://172.27.0.37:1960/c2/lc/ms/cust/seller/confirmItems/itemMapping

#localhost
#customer.confirm.item.api=http://localhost:1960/c2/lc/ms/cust/seller/confirmItems/itemMapping
