## Added Correct Port Number
server.port=1960
seller.new.launch.days=10


api.base.path=/c2/lc/ms/cust
#web.base.url=http://localhost:3000

fetch.max.size.limit=5000

hash.algorithm=HmacSHA256
aes.key = 9z$C&F)J@NcRfUjWnZr4u7x!A%D*G-Ka
aes.iv = fSdtT8WMdzVpXDcM

spring.liquibase.enabled=false

#cors.url=http://localhost:3000
cors.url=*

#Azure blob storage
azure.storage.connection.string=DefaultEndpointsProtocol=https;AccountName=devloblob;AccountKey=3w8pgNcvIhqgHK0t9G/NbWleVRqCgSA9ad1eeXip716QxY4EL9aMtpH8jx0BK0sPz1mUScBLP92wrUvXQ==;EndpointSuffix=core.windows.net
azure.storage.container.name=mslo

#Dev
auth.register.api=http://10.0.88.174:3460/lc/ms/c2/srv/l/register/web
create.token.api=http://10.0.88.174:3460/lc/ms/c2/srv/l/create/token/key
auth.login.api=http://10.0.88.174:3460/lc/ms/c2/srv/l/login/web
auth.password.api=http://10.0.88.174:3460/lc/ms/c2/password/send/password
web.base.url=https://dev-lc-web.livc.in

#localhost
#auth.register.api=http://localhost:3460/lc/ms/c2/srv/l/register/web
#auth.login.api=http://localhost:3460/lc/ms/c2/srv/l/login/web
#auth.password.api=http://localhost:3460/lc/ms/c2/password/send/password
#create.token.api=http://localhost:3460/lc/ms/c2/srv/l/create/token/key

#Email Service
spring.email.from = noreply.microservices@c2info.com
spring.email.to = gautham.raju@c2info.com
spring.email.url = https://dev-lc.livc.in/comm/email/p/send

secret.key=ajay123

#DEV
notification.api.url=http://10.0.252.149:1972/c2/lc/ms/notification/p/notification

#Local
#notification.api.url = http://localhost:1972/c2/lc/ms/notification/p/notification

#local
cart.count.api.url = http://localhost:1264/c2/lc/ms/ord/l/cart/count

lost.stock.days = 10
